cwd=$(pwd);
echo "Termux metasploit-framework installer by NightmareGaurav";
echo "Installing required packages...";
apt update && apt upgrade;
apt install -y autoconf bison clang coreutils curl findutils git apr apr-util libffi-dev libgmp-dev libpcap-dev postgresql-dev readline-dev libsqlite-dev openssl-dev libtool libxml2-dev libxslt-dev ncurses-dev pkg-config wget make ruby-dev libgrpc-dev termux-tools ncurses-utils ncurses unzip zip tar postgresql termux-elf-cleaner *repo*;
apt install ethtool -y;
cd $HOME;
echo "Cloning file...";
git clone https://github.com/rapid7/metasploit-framework.git;
cd $HOME/metasploit-framework;
echo "Installing required gems...";
gem install bundler;
bundle install -j5;
echo "Gems installed...";
cd $HOME;
echo "Giving permission...";
chmod -R 777 metasploit-framework;
echo "Cleaning elf...";
termux-elf-cleaner /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/pg-0.20.0/lib/pg_ext.so;
echo "Setting up database...";
echo "production:" > $HOME/metasploit-framework/config/database.yml;
echo "adapter: postgresql" >> $HOME/metasploit-framework/config/database.yml;
echo "database: msf_database" >> $HOME/metasploit-framework/config/database.yml;
echo "username: msf" >> $HOME/metasploit-framework/config/database.yml;
echo "password: " >> $HOME/metasploit-framework/config/database.yml;
echo "host: 127.0.0.1" >> $HOME/metasploit-framework/config/database.yml;
echo "port: 5432" >> $HOME/metasploit-framework/config/database.yml;
echo "pool: 75" >> $HOME/metasploit-framework/config/database.yml;
echo "timeout: 5" >> $HOME/metasploit-framework/config/database.yml;
mkdir -p $PREFIX/var/lib/postgresql;
initdb $PREFIX/var/lib/postgresql;
pg_ctl -D $PREFIX/var/lib/postgresql start;
createuser msf;
createdb msf_database;
pg_ctl -D $PREFIX/var/lib/postgresql stop;
echo "Giving final touch...";
chmod -R 777 $HOME/metasploit-framework;
echo "alias dbs='pg_ctl -D $PREFIX/var/lib/postgresql start'" >> $HOME/.bashrc;
echo "alias dbss='pg_ctl -D $PREFIX/var/lib/postgresql stop'" >> $HOME/.bashrc;
echo "alias msfconsole='$HOME/metasploit-framework/msfconsole'" >> $HOME/.bashrc;
echo "alias msfd='$HOME/metasploit-framework/msfd'" >> $HOME/.bashrc;
echo "alias msfdb='$HOME/metasploit-framework/msfdb'" >> $HOME/.bashrc;
echo "alias msfdb_ws='$HOME/metasploit-framework/msfdb_ws'" >> $HOME/.bashrc;
echo "alias msfrpc='$HOME/metasploit-framework/msfrpc'" >> $HOME/.bashrc;
echo "alias msfrpcd='$HOME/metasploit-framework/msfrpcd'" >> $HOME/.bashrc;
echo "alias msfupdate='$HOME/metasploit-framework/msfupdate'" >> $HOME/.bashrc;
echo "alias msfvenom='$HOME/metasploit-framework/msfvenom'" >> $HOME/.bashrc;
echo "Don't remove metasploit-framework folder from your $HOME...";
echo "Close this terminal session, reopen another and hit metasploit commands to start...";
echo "Done.";
